# Generated by Django 4.1.7 on 2023-04-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_user_educational_institution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Ученик', 'Ученик'), ('Студент', 'Студент'), ('Учитель', 'Учитель'), ('Родитель', 'Родитель')], max_length=50, verbose_name='Статус'),
        ),
    ]
