# Generated by Django 4.1.7 on 2023-04-19 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_user_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
    ]
