# Generated by Django 4.1.7 on 2023-03-14 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('track', models.CharField(choices=[('Знание', 'Знание'), ('Развитие', 'Развитие'), ('Карьера в ИНК', 'Карьера в ИНК')], max_length=50, verbose_name='Трэк')),
                ('lesson_format', models.CharField(max_length=120, verbose_name='Формат')),
                ('lesson_date', models.DateField(verbose_name='Дата')),
                ('lesson_time', models.CharField(max_length=50, verbose_name='Время')),
                ('theme', models.TextField(verbose_name='Тема')),
                ('level', models.CharField(blank=True, max_length=120, verbose_name='Уровень подготовки')),
                ('audience', models.CharField(blank=True, max_length=120, verbose_name='Целевая аудитория')),
                ('teacher', models.CharField(blank=True, max_length=255, verbose_name='Преподаватель')),
                ('place', models.CharField(max_length=255, verbose_name='Место')),
                ('required_items', models.CharField(blank=True, max_length=255, verbose_name='Что взять с собой')),
                ('count_seats', models.IntegerField(default=0, verbose_name='Кол-во мест')),
                ('count_records', models.IntegerField(default=0, verbose_name='Кол-во записей')),
                ('points', models.IntegerField(default=5, verbose_name='Кол-во баллов')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершенно')),
            ],
        ),
        migrations.CreateModel(
            name='RecordsLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presence', models.BooleanField(blank=True, default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='timetable.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
