# Generated by Django 4.1.7 on 2023-03-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_alter_lesson_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='level',
        ),
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('Ученик', 'Ученик'), ('Студент', 'Студент'), ('Родитель', 'Родитель')], default='Ученик', max_length=120, verbose_name='Статус участника'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='track',
            field=models.CharField(blank=True, max_length=50, verbose_name='Трэк'),
        ),
    ]
